
package vista;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Automovil;
import modelo.Moto;
import modelo.Avion;
import modelo.Helicoptero;
import java.awt.Color;

public class frm_vehiculo extends javax.swing.JFrame {

    DefaultTableModel t_vehiculo;
    Automovil obj_automovil;
    Moto obj_moto;
    Avion obj_avion;
    Helicoptero obj_helicoptero;
    public frm_vehiculo() {
        initComponents();
        cmb_tipo.addItem("Automovil");
        cmb_tipo.addItem("Moto");
        cmb_tipo.addItem("Avion");
        cmb_tipo.addItem("Helicoptero");
        t_vehiculo = new DefaultTableModel();
        String encabezado[]={"Tipo","Motor","Color","Marca","Asientos","Faros","Placa","Cilindros","Llantas","Ventanas","Puertas","Chasis","Horquilla","Turbinas","Alerones","Helice","Rotor"};
        t_vehiculo.setColumnIdentifiers(encabezado);
        tbl_vehiculo.setModel(t_vehiculo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_tipo = new javax.swing.JLabel();
        lbl_motor = new javax.swing.JLabel();
        txt_motor = new javax.swing.JTextField();
        lbl_color = new javax.swing.JLabel();
        txt_color = new javax.swing.JTextField();
        lbl_marca = new javax.swing.JLabel();
        txt_marca = new javax.swing.JTextField();
        lbl_asientos = new javax.swing.JLabel();
        txt_asientos = new javax.swing.JTextField();
        lbl_faros = new javax.swing.JLabel();
        txt_faros = new javax.swing.JTextField();
        lbl_placa = new javax.swing.JLabel();
        txt_placa = new javax.swing.JTextField();
        lbl_cilindros = new javax.swing.JLabel();
        txt_cilindros = new javax.swing.JTextField();
        lbl_llantas = new javax.swing.JLabel();
        txt_llantas = new javax.swing.JTextField();
        lbl_chasis = new javax.swing.JLabel();
        txt_chasis = new javax.swing.JTextField();
        lbl_puertas = new javax.swing.JLabel();
        txt_puertas = new javax.swing.JTextField();
        lbl_horquilla = new javax.swing.JLabel();
        txt_horquilla = new javax.swing.JTextField();
        lbl_ventanas = new javax.swing.JLabel();
        txt_ventanas = new javax.swing.JTextField();
        lbl_turbinas = new javax.swing.JLabel();
        txt_turbinas = new javax.swing.JTextField();
        lbl_alerones = new javax.swing.JLabel();
        txt_alerones = new javax.swing.JTextField();
        lbl_helices = new javax.swing.JLabel();
        txt_helice = new javax.swing.JTextField();
        lbl_rotores = new javax.swing.JLabel();
        txt_rotor = new javax.swing.JTextField();
        btn_agregar = new javax.swing.JButton();
        cmb_tipo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_vehiculo = new javax.swing.JTable();
        btn_salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 500));
        jPanel1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPanel1PropertyChange(evt);
            }
        });

        lbl_tipo.setText("Tipo:");
        lbl_tipo.setPreferredSize(new java.awt.Dimension(60, 14));

        lbl_motor.setText("Motor:");
        lbl_motor.setPreferredSize(new java.awt.Dimension(60, 14));

        txt_motor.setPreferredSize(new java.awt.Dimension(130, 30));

        lbl_color.setText("Color:");
        lbl_color.setPreferredSize(new java.awt.Dimension(60, 14));

        txt_color.setPreferredSize(new java.awt.Dimension(130, 30));

        lbl_marca.setText("Marca:");
        lbl_marca.setPreferredSize(new java.awt.Dimension(60, 14));

        txt_marca.setPreferredSize(new java.awt.Dimension(130, 30));

        lbl_asientos.setText("Asientos:");
        lbl_asientos.setPreferredSize(new java.awt.Dimension(60, 14));

        txt_asientos.setPreferredSize(new java.awt.Dimension(130, 30));
        txt_asientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_asientosActionPerformed(evt);
            }
        });
        txt_asientos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_asientosKeyReleased(evt);
            }
        });

        lbl_faros.setText("Faros:");
        lbl_faros.setPreferredSize(new java.awt.Dimension(60, 14));

        txt_faros.setPreferredSize(new java.awt.Dimension(130, 30));
        txt_faros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_farosKeyReleased(evt);
            }
        });

        lbl_placa.setText("Placa:");
        lbl_placa.setPreferredSize(new java.awt.Dimension(60, 14));

        txt_placa.setPreferredSize(new java.awt.Dimension(130, 30));
        txt_placa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_placaActionPerformed(evt);
            }
        });
        txt_placa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_placaKeyReleased(evt);
            }
        });

        lbl_cilindros.setText("Cilindros");
        lbl_cilindros.setPreferredSize(new java.awt.Dimension(60, 14));

        txt_cilindros.setPreferredSize(new java.awt.Dimension(130, 30));

        lbl_llantas.setText("Llantas:");
        lbl_llantas.setPreferredSize(new java.awt.Dimension(60, 14));

        txt_llantas.setPreferredSize(new java.awt.Dimension(130, 30));
        txt_llantas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_llantasKeyReleased(evt);
            }
        });

        lbl_chasis.setText("Chasis:");
        lbl_chasis.setPreferredSize(new java.awt.Dimension(60, 14));

        txt_chasis.setPreferredSize(new java.awt.Dimension(130, 30));

        lbl_puertas.setText("Puertas:");
        lbl_puertas.setPreferredSize(new java.awt.Dimension(60, 14));

        txt_puertas.setPreferredSize(new java.awt.Dimension(130, 30));
        txt_puertas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_puertasKeyReleased(evt);
            }
        });

        lbl_horquilla.setText("Horquilla:");
        lbl_horquilla.setPreferredSize(new java.awt.Dimension(60, 14));

        txt_horquilla.setPreferredSize(new java.awt.Dimension(130, 30));

        lbl_ventanas.setText("Ventanas:");
        lbl_ventanas.setPreferredSize(new java.awt.Dimension(60, 14));

        txt_ventanas.setPreferredSize(new java.awt.Dimension(130, 30));
        txt_ventanas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_ventanasKeyReleased(evt);
            }
        });

        lbl_turbinas.setText("Turbinas:");
        lbl_turbinas.setPreferredSize(new java.awt.Dimension(60, 14));

        txt_turbinas.setPreferredSize(new java.awt.Dimension(130, 30));
        txt_turbinas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_turbinasKeyReleased(evt);
            }
        });

        lbl_alerones.setText("Alerones:");
        lbl_alerones.setPreferredSize(new java.awt.Dimension(60, 14));

        txt_alerones.setPreferredSize(new java.awt.Dimension(130, 30));
        txt_alerones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_aleronesKeyReleased(evt);
            }
        });

        lbl_helices.setText("Helice:");
        lbl_helices.setPreferredSize(new java.awt.Dimension(60, 14));

        txt_helice.setPreferredSize(new java.awt.Dimension(130, 30));
        txt_helice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_heliceKeyReleased(evt);
            }
        });

        lbl_rotores.setText("Rotor");
        lbl_rotores.setPreferredSize(new java.awt.Dimension(60, 14));

        txt_rotor.setPreferredSize(new java.awt.Dimension(130, 30));
        txt_rotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rotorActionPerformed(evt);
            }
        });
        txt_rotor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_rotorKeyReleased(evt);
            }
        });

        btn_agregar.setBackground(new java.awt.Color(255, 0, 51));
        btn_agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/touchscreen_book_bookmark_ebook_icon_191190.png"))); // NOI18N
        btn_agregar.setPreferredSize(new java.awt.Dimension(100, 50));
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        cmb_tipo.setToolTipText("");
        cmb_tipo.setPreferredSize(new java.awt.Dimension(130, 20));
        cmb_tipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_tipoItemStateChanged(evt);
            }
        });
        cmb_tipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cmb_tipoMouseReleased(evt);
            }
        });
        cmb_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_tipoActionPerformed(evt);
            }
        });

        tbl_vehiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl_vehiculo);

        btn_salir.setBackground(new java.awt.Color(255, 0, 0));
        btn_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/sali.png"))); // NOI18N
        btn_salir.setPreferredSize(new java.awt.Dimension(100, 50));
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(210, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_faros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_faros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_motor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_motor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lbl_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txt_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lbl_asientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txt_asientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(126, 126, 126)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_horquilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_horquilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(lbl_llantas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txt_llantas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(lbl_cilindros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txt_cilindros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(lbl_placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txt_placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbl_puertas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_puertas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbl_chasis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_chasis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(117, 117, 117)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_alerones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_alerones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_turbinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_turbinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_ventanas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txt_ventanas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lbl_rotores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txt_rotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lbl_helices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txt_helice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(223, 223, 223))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142)
                        .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(464, 464, 464))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_ventanas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_ventanas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_turbinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_turbinas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_alerones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_alerones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_helices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_helice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_rotores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_rotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_motor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_motor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_asientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_asientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_faros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_faros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_cilindros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_cilindros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_llantas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_llantas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_chasis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_chasis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_puertas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_puertas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_horquilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_horquilla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_rotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rotorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rotorActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
        // TODO add your handling code here:
        String con = cmb_tipo.getSelectedItem().toString();
        
        switch(con){
            case "Automovil":
                int puertas = Integer.parseInt(txt_puertas.getText());
                int llantas = Integer.parseInt(txt_llantas.getText());
                int asientos = Integer.parseInt(txt_asientos.getText());
                int faros = Integer.parseInt(txt_faros.getText());
                obj_automovil = new Automovil(txt_chasis.getText(),puertas,txt_placa.getText(),txt_cilindros.getText(),llantas,con,txt_motor.getText(),txt_color.getText(),txt_marca.getText(),asientos,faros);
                String datosa[] = obj_automovil.agregar();
                t_vehiculo.addRow(datosa);
                JOptionPane.showMessageDialog(rootPane, "Ingreso Correcto","Mensaje",JOptionPane.INFORMATION_MESSAGE);
            break;
            case "Moto":
                llantas = Integer.parseInt(txt_llantas.getText());
                asientos = Integer.parseInt(txt_asientos.getText());
                faros = Integer.parseInt(txt_faros.getText());
                obj_moto = new Moto(txt_horquilla.getText(),txt_placa.getText(),txt_cilindros.getText(),llantas,con,txt_motor.getText(),txt_color.getText(),txt_marca.getText(),asientos,faros);
                String datosm[] = obj_moto.agregar();
                t_vehiculo.addRow(datosm);
                JOptionPane.showMessageDialog(rootPane, "Ingreso Correcto","Mensaje",JOptionPane.INFORMATION_MESSAGE);
            break;
            case "Avion":
                asientos = Integer.parseInt(txt_asientos.getText());
                faros = Integer.parseInt(txt_faros.getText());
                puertas = Integer.parseInt(txt_puertas.getText());
                int ventanas = Integer.parseInt(txt_ventanas.getText());
                int turbinas = Integer.parseInt(txt_turbinas.getText());
                int alerones = Integer.parseInt(txt_alerones.getText());
                obj_avion = new Avion(turbinas,alerones,ventanas,puertas,con,txt_motor.getText(),txt_color.getText(),txt_marca.getText(),asientos,faros);
                String datosv[] = obj_avion.agregar();
                t_vehiculo.addRow(datosv);
                JOptionPane.showMessageDialog(rootPane, "Ingreso Correcto","Mensaje",JOptionPane.INFORMATION_MESSAGE);
            break;
            case "Helicoptero":
                int helice = Integer.parseInt(txt_helice.getText());
                int rotor = Integer.parseInt(txt_rotor.getText());
                puertas = Integer.parseInt(txt_puertas.getText());
                ventanas = Integer.parseInt(txt_ventanas.getText());
                asientos = Integer.parseInt(txt_asientos.getText());
                faros = Integer.parseInt(txt_faros.getText());
                obj_helicoptero = new Helicoptero(helice,rotor,ventanas,puertas,con,txt_motor.getText(),txt_color.getText(),txt_marca.getText(),asientos,faros);
                String datosh[] = obj_helicoptero.agregar();
                t_vehiculo.addRow(datosh);
                JOptionPane.showMessageDialog(rootPane, "Ingreso Correcto","Mensaje",JOptionPane.INFORMATION_MESSAGE);
            break;
        }
        
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void txt_placaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_placaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_placaActionPerformed

    private void jPanel1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jPanel1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1PropertyChange

    private void cmb_tipoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb_tipoMouseReleased
        // TODO add your handling code here:
         /*String con = cmb_tipo.getSelectedItem().toString();
         JOptionPane.showMessageDialog(rootPane, "Ingreso Correcto"+con,"Mensaje",JOptionPane.INFORMATION_MESSAGE);*/
        /*if (cmb_tipo.getSelectedItem()..matches("[C]{1}[0-9]{3}")){
            lbl_codigo.setForeground(Color.black);
            lbl_codigo.setText("Codigo");
        }*/
    }//GEN-LAST:event_cmb_tipoMouseReleased

    private void cmb_tipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_tipoItemStateChanged
        // TODO add your handling code here:
        String con = cmb_tipo.getSelectedItem().toString();
        switch(con){
            case "Automovil":
            txt_placa.setEnabled(true);
            txt_cilindros.setEnabled(true);
            txt_llantas.setEnabled(true);
            txt_chasis.setEnabled(true);
            txt_puertas.setEnabled(true);
            txt_horquilla.setEnabled(false);
            txt_ventanas.setEnabled(false);
            txt_turbinas.setEnabled(false);
            txt_alerones.setEnabled(false);
            txt_helice.setEnabled(false);
            txt_rotor.setEnabled(false);
            
            lbl_placa.setForeground(Color.black);
            lbl_cilindros.setForeground(Color.black);
            lbl_llantas.setForeground(Color.black);
            lbl_chasis.setForeground(Color.black);
            lbl_puertas.setForeground(Color.black);
            lbl_horquilla.setForeground(Color.red);
            lbl_ventanas.setForeground(Color.red);
            lbl_turbinas.setForeground(Color.red);
            lbl_alerones.setForeground(Color.red);
            lbl_helices.setForeground(Color.red);
            lbl_rotores.setForeground(Color.red);
            break;
            
            case "Moto":
            txt_placa.setEnabled(true);
            txt_cilindros.setEnabled(true);
            txt_llantas.setEnabled(true);
            txt_chasis.setEnabled(false);
            txt_puertas.setEnabled(false);
            txt_horquilla.setEnabled(true);
            txt_ventanas.setEnabled(false);
            txt_turbinas.setEnabled(false);
            txt_alerones.setEnabled(false);
            txt_helice.setEnabled(false);
            txt_rotor.setEnabled(false);
            
            lbl_placa.setForeground(Color.black);
            lbl_cilindros.setForeground(Color.black);
            lbl_llantas.setForeground(Color.black);
            lbl_chasis.setForeground(Color.red);
            lbl_puertas.setForeground(Color.red);
            lbl_horquilla.setForeground(Color.black);
            lbl_ventanas.setForeground(Color.red);
            lbl_turbinas.setForeground(Color.red);
            lbl_alerones.setForeground(Color.red);
            lbl_helices.setForeground(Color.red);
            lbl_rotores.setForeground(Color.red);
            break;
            
            case "Avion":
            txt_placa.setEnabled(false);
            txt_cilindros.setEnabled(false);
            txt_llantas.setEnabled(false);
            txt_chasis.setEnabled(false);
            txt_puertas.setEnabled(true);
            txt_horquilla.setEnabled(false);
            txt_ventanas.setEnabled(true);
            txt_turbinas.setEnabled(true);
            txt_alerones.setEnabled(true);
            txt_helice.setEnabled(false);
            txt_rotor.setEnabled(false);
            
            lbl_placa.setForeground(Color.red);
            lbl_cilindros.setForeground(Color.red);
            lbl_llantas.setForeground(Color.red);
            lbl_chasis.setForeground(Color.red);
            lbl_puertas.setForeground(Color.black);
            lbl_horquilla.setForeground(Color.red);
            lbl_ventanas.setForeground(Color.black);
            lbl_turbinas.setForeground(Color.black);
            lbl_alerones.setForeground(Color.black);
            lbl_helices.setForeground(Color.red);
            lbl_rotores.setForeground(Color.red);
            break;
            
            case "Helicoptero":
            txt_placa.setEnabled(false);
            txt_cilindros.setEnabled(false);
            txt_llantas.setEnabled(false);
            txt_chasis.setEnabled(false);
            txt_puertas.setEnabled(true);
            txt_horquilla.setEnabled(false);
            txt_ventanas.setEnabled(true);
            txt_turbinas.setEnabled(false);
            txt_alerones.setEnabled(false);
            txt_helice.setEnabled(true);
            txt_rotor.setEnabled(true);
            
            lbl_placa.setForeground(Color.red);
            lbl_cilindros.setForeground(Color.red);
            lbl_llantas.setForeground(Color.red);
            lbl_chasis.setForeground(Color.red);
            lbl_puertas.setForeground(Color.black);
            lbl_horquilla.setForeground(Color.red);
            lbl_ventanas.setForeground(Color.black);
            lbl_turbinas.setForeground(Color.red);
            lbl_alerones.setForeground(Color.red);
            lbl_helices.setForeground(Color.black);
            lbl_rotores.setForeground(Color.black);
            break;
        }
    }//GEN-LAST:event_cmb_tipoItemStateChanged

    private void txt_asientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_asientosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_asientosActionPerformed

    private void txt_asientosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_asientosKeyReleased
        // TODO add your handling code here:
        if (txt_asientos.getText().matches("[0-9]{1,3}")){
            lbl_asientos.setForeground(Color.black);
            lbl_asientos.setText("Asientos:");
        }else{
            lbl_asientos.setForeground(Color.red);
            lbl_asientos.setText("Error..");
        }
    }//GEN-LAST:event_txt_asientosKeyReleased

    private void txt_farosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_farosKeyReleased
        // TODO add your handling code here:
        if (txt_faros.getText().matches("[0-9]{1,2}")){
            lbl_faros.setForeground(Color.black);
            lbl_faros.setText("Faros:");
        }else{
            lbl_faros.setForeground(Color.red);
            lbl_faros.setText("Error..");
        }
    }//GEN-LAST:event_txt_farosKeyReleased

    private void txt_placaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_placaKeyReleased
        // TODO add your handling code here:
        if (txt_placa.getText().matches("[P,M]{1}[0-9]{3}[A-Z]{3}")){
            lbl_placa.setForeground(Color.black);
            lbl_placa.setText("Placa:");
        }else{
            lbl_placa.setForeground(Color.red);
            lbl_placa.setText("Error..(P...)");
        }
    }//GEN-LAST:event_txt_placaKeyReleased

    private void txt_llantasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_llantasKeyReleased
        // TODO add your handling code here:
        if (txt_llantas.getText().matches("[2-8]{1}")){
            lbl_llantas.setForeground(Color.black);
            lbl_llantas.setText("Llantas:");
        }else{
            lbl_llantas.setForeground(Color.red);
            lbl_llantas.setText("Error..");
        }
    }//GEN-LAST:event_txt_llantasKeyReleased

    private void txt_puertasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_puertasKeyReleased
        // TODO add your handling code here:
        if (txt_puertas.getText().matches("[1-9]{1}")){
            lbl_puertas.setForeground(Color.black);
            lbl_puertas.setText("Puertas:");
        }else{
            lbl_puertas.setForeground(Color.red);
            lbl_puertas.setText("Error..");
        }
    }//GEN-LAST:event_txt_puertasKeyReleased

    private void txt_ventanasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ventanasKeyReleased
        // TODO add your handling code here:
        if (txt_ventanas.getText().matches("[0-9]{1,3}")){
            lbl_ventanas.setForeground(Color.black);
            lbl_ventanas.setText("Ventanas:");
        }else{
            lbl_ventanas.setForeground(Color.red);
            lbl_ventanas.setText("Error..");
        }
    }//GEN-LAST:event_txt_ventanasKeyReleased

    private void txt_turbinasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_turbinasKeyReleased
        // TODO add your handling code here:
        if (txt_turbinas.getText().matches("[1-9]{1}")){
            lbl_turbinas.setForeground(Color.black);
            lbl_turbinas.setText("Turbinas:");
        }else{
            lbl_turbinas.setForeground(Color.red);
            lbl_turbinas.setText("Error..");
        }
    }//GEN-LAST:event_txt_turbinasKeyReleased

    private void txt_aleronesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_aleronesKeyReleased
        // TODO add your handling code here:
        if (txt_alerones.getText().matches("[1-9]{1}")){
            lbl_alerones.setForeground(Color.black);
            lbl_alerones.setText("Alerones:");
        }else{
            lbl_alerones.setForeground(Color.red);
            lbl_alerones.setText("Error..");
        }
    }//GEN-LAST:event_txt_aleronesKeyReleased

    private void txt_heliceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_heliceKeyReleased
        // TODO add your handling code here:
        if (txt_helice.getText().matches("[1-9]{1}")){
            lbl_helices.setForeground(Color.black);
            lbl_helices.setText("Helice:");
        }else{
            lbl_helices.setForeground(Color.red);
            lbl_helices.setText("Error..");
        }
    }//GEN-LAST:event_txt_heliceKeyReleased

    private void txt_rotorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_rotorKeyReleased
        // TODO add your handling code here:
        if (txt_rotor.getText().matches("[1-9]{1}")){
            lbl_rotores.setForeground(Color.black);
            lbl_rotores.setText("Rotor:");
        }else{
            lbl_rotores.setForeground(Color.red);
            lbl_rotores.setText("Error..");
        }
    }//GEN-LAST:event_txt_rotorKeyReleased

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_salirActionPerformed

    private void cmb_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_tipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_tipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_vehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_vehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_vehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_vehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frm_vehiculo().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_salir;
    private javax.swing.JComboBox<String> cmb_tipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_alerones;
    private javax.swing.JLabel lbl_asientos;
    private javax.swing.JLabel lbl_chasis;
    private javax.swing.JLabel lbl_cilindros;
    private javax.swing.JLabel lbl_color;
    private javax.swing.JLabel lbl_faros;
    private javax.swing.JLabel lbl_helices;
    private javax.swing.JLabel lbl_horquilla;
    private javax.swing.JLabel lbl_llantas;
    private javax.swing.JLabel lbl_marca;
    private javax.swing.JLabel lbl_motor;
    private javax.swing.JLabel lbl_placa;
    private javax.swing.JLabel lbl_puertas;
    private javax.swing.JLabel lbl_rotores;
    private javax.swing.JLabel lbl_tipo;
    private javax.swing.JLabel lbl_turbinas;
    private javax.swing.JLabel lbl_ventanas;
    private javax.swing.JTable tbl_vehiculo;
    private javax.swing.JTextField txt_alerones;
    private javax.swing.JTextField txt_asientos;
    private javax.swing.JTextField txt_chasis;
    private javax.swing.JTextField txt_cilindros;
    private javax.swing.JTextField txt_color;
    private javax.swing.JTextField txt_faros;
    private javax.swing.JTextField txt_helice;
    private javax.swing.JTextField txt_horquilla;
    private javax.swing.JTextField txt_llantas;
    private javax.swing.JTextField txt_marca;
    private javax.swing.JTextField txt_motor;
    private javax.swing.JTextField txt_placa;
    private javax.swing.JTextField txt_puertas;
    private javax.swing.JTextField txt_rotor;
    private javax.swing.JTextField txt_turbinas;
    private javax.swing.JTextField txt_ventanas;
    // End of variables declaration//GEN-END:variables
}
